#!/usr/bin/env bash
# AUTO-GENERATED by tools/gen_pieces.py
set -euo pipefail
cd "$(dirname "$0")"
OSCAD="${OPENSCAD:-openscad}"
mkdir -p stl
"$OSCAD" -D PIECE=1 -D COL=1 -o stl/piece1_black.stl src/parts/piece.scad 2>stl/p1b.log && echo "  ok piece1_black"
"$OSCAD" -D PIECE=1 -D COL=2 -o stl/piece1_white.stl src/parts/piece.scad 2>stl/p1w.log && echo "  ok piece1_white"
"$OSCAD" -D PIECE=1 -D COL=3 -o stl/piece1_clear.stl src/parts/piece.scad 2>stl/p1c.log && echo "  ok piece1_clear"
"$OSCAD" -D PIECE=2 -D COL=1 -o stl/piece2_black.stl src/parts/piece.scad 2>stl/p2b.log && echo "  ok piece2_black"
"$OSCAD" -D PIECE=2 -D COL=2 -o stl/piece2_white.stl src/parts/piece.scad 2>stl/p2w.log && echo "  ok piece2_white"
"$OSCAD" -D PIECE=2 -D COL=3 -o stl/piece2_clear.stl src/parts/piece.scad 2>stl/p2c.log && echo "  ok piece2_clear"
"$OSCAD" -D PIECE=3 -D COL=1 -o stl/piece3_black.stl src/parts/piece.scad 2>stl/p3b.log && echo "  ok piece3_black"
"$OSCAD" -D PIECE=3 -D COL=2 -o stl/piece3_white.stl src/parts/piece.scad 2>stl/p3w.log && echo "  ok piece3_white"
"$OSCAD" -D PIECE=3 -D COL=3 -o stl/piece3_clear.stl src/parts/piece.scad 2>stl/p3c.log && echo "  ok piece3_clear"
"$OSCAD" -D PIECE=4 -D COL=1 -o stl/piece4_black.stl src/parts/piece.scad 2>stl/p4b.log && echo "  ok piece4_black"
"$OSCAD" -D PIECE=4 -D COL=2 -o stl/piece4_white.stl src/parts/piece.scad 2>stl/p4w.log && echo "  ok piece4_white"
"$OSCAD" -D PIECE=4 -D COL=3 -o stl/piece4_clear.stl src/parts/piece.scad 2>stl/p4c.log && echo "  ok piece4_clear"
"$OSCAD" -D PIECE=5 -D COL=1 -o stl/piece5_black.stl src/parts/piece.scad 2>stl/p5b.log && echo "  ok piece5_black"
"$OSCAD" -D PIECE=5 -D COL=2 -o stl/piece5_white.stl src/parts/piece.scad 2>stl/p5w.log && echo "  ok piece5_white"
"$OSCAD" -D PIECE=5 -D COL=3 -o stl/piece5_clear.stl src/parts/piece.scad 2>stl/p5c.log && echo "  ok piece5_clear"
"$OSCAD" -D PIECE=6 -D COL=1 -o stl/piece6_black.stl src/parts/piece.scad 2>stl/p6b.log && echo "  ok piece6_black"
"$OSCAD" -D PIECE=6 -D COL=2 -o stl/piece6_white.stl src/parts/piece.scad 2>stl/p6w.log && echo "  ok piece6_white"
"$OSCAD" -D PIECE=6 -D COL=3 -o stl/piece6_clear.stl src/parts/piece.scad 2>stl/p6c.log && echo "  ok piece6_clear"
python3 tools/make_3mf.py stl/piece1_black.stl stl/piece1_white.stl stl/piece1_clear.stl stl/piece1_3color.3mf
python3 tools/make_3mf.py stl/piece2_black.stl stl/piece2_white.stl stl/piece2_clear.stl stl/piece2_3color.3mf
python3 tools/make_3mf.py stl/piece3_black.stl stl/piece3_white.stl stl/piece3_clear.stl stl/piece3_3color.3mf
python3 tools/make_3mf.py stl/piece4_black.stl stl/piece4_white.stl stl/piece4_clear.stl stl/piece4_3color.3mf
python3 tools/make_3mf.py stl/piece5_black.stl stl/piece5_white.stl stl/piece5_clear.stl stl/piece5_3color.3mf
python3 tools/make_3mf.py stl/piece6_black.stl stl/piece6_white.stl stl/piece6_clear.stl stl/piece6_3color.3mf
