#!/usr/bin/env python3
"""Regenerate docs/gallery/ — one dashboard SVG + stats line per showcase build.

Run from the project root: uv run python scripts/make_gallery.py
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

from signforge.params import SignParams
from signforge.pipeline import build

ROOT = Path(__file__).parent.parent
GALLERY = ROOT / "docs" / "gallery"

SHOWS: list[dict] = [
    {
        "name": "open-neon",
        "blurb": "Neon tubes, V8 facet lens, 17mm pixels, H2D",
        "params": {
            "content": {"text": "OPEN", "cap_height_mm": 180},
            "style": {"kind": "neon", "backer": "tile"},
        },
    },
    {
        "name": "cafe-channel",
        "blurb": "Channel letters, press-fit faces, no backer",
        "params": {
            "content": {"text": "CAFE", "cap_height_mm": 140},
            "style": {"kind": "channel", "backer": "none"},
            "leds": {"kind": "none"},
            "texture": {"mode": "none"},
        },
    },
    {
        "name": "halo-b",
        "blurb": "Halo/backlit letter, rear pixel racetrack, standoffs",
        "params": {
            "content": {"text": "B", "cap_height_mm": 150},
            "style": {"kind": "halo"},
            "texture": {"mode": "none"},
        },
    },
    {
        "name": "star-shape",
        "blurb": "SVG shape art through the neon skeletonizer",
        "params": {
            "content": {
                "mode": "art",
                "art_path": str(ROOT / "tests" / "assets" / "svg" / "star.svg"),
                "art_target_height_mm": 200,
            },
            "style": {"kind": "neon", "backer": "contour"},
            "texture": {"mode": "none"},
        },
    },
    {
        "name": "script-neon",
        "blurb": "Script font (Pacifico) as connected neon",
        "params": {
            "content": {
                "text": "glow",
                "cap_height_mm": 140,
                "font_path": str(ROOT / "tests" / "assets" / "fonts" / "Pacifico-Regular.ttf"),
            },
            "style": {"kind": "neon", "backer": "tile"},
            "texture": {"mode": "none"},
        },
    },
]


def main() -> None:
    GALLERY.mkdir(parents=True, exist_ok=True)
    rows = []
    for show in SHOWS:
        cfg = dict(show["params"])
        cfg["name"] = show["name"]
        params = SignParams.model_validate(cfg)
        with tempfile.TemporaryDirectory() as td:
            result = build(params, td)
            html = (Path(td) / "preview" / "index.html").read_text()
        svg = re.search(r"<svg.*?</svg>", html, re.S).group(0)
        (GALLERY / f"{show['name']}.svg").write_text(svg)
        s = result.stats
        rows.append(
            f"### {show['name']}\n\n{show['blurb']} — "
            f"{s['sign_mm'][0]:.0f}×{s['sign_mm'][1]:.0f} mm · {s['pieces']} piece(s) · "
            f"{s['pixels']} px · {s['total_grams_petg']:.0f} g\n\n"
            f"![{show['name']}]({show['name']}.svg)\n"
        )
        print(f"  ✓ {show['name']}: {s['pieces']} piece(s), {s['pixels']} px")

    (GALLERY / "README.md").write_text(
        "# Gallery\n\nGenerated by `scripts/make_gallery.py` — every image is the "
        "real production dashboard of a real build (geometry, pixels, wiring, seams).\n\n"
        + "\n".join(rows)
    )
    print(f"gallery written to {GALLERY}")


if __name__ == "__main__":
    main()
