#!/usr/bin/env python3
"""Baked geometry for the CHARGE word sign, emitted as a C header for the
tedxfargo WLED usermod. Mirrors tools/gen_wiring.py's ledmap() grid mapping
EXACTLY so COL/ROW agree with the flashed ledmap.json."""
import math

LETTERS = "CHARGE"

def compute(pixels, w_mm, h_mm, ox, oy, cell):
    px = sorted(pixels, key=lambda p: p["chain"])
    n = len(px)
    W = math.ceil(w_mm / cell)
    H = math.ceil(h_mm / cell)
    col = [min(W - 1, int((p["x"] - ox) / cell)) for p in px]
    row = [min(H - 1, int((h_mm - (p["y"] - oy) - 0.001) / cell)) for p in px]  # 0 = top
    letter = [LETTERS.index(p["letter"]) for p in px]
    yext = {}
    for p in px:
        lo, hi = yext.get(p["letter"], (p["y"], p["y"]))
        yext[p["letter"]] = (min(lo, p["y"]), max(hi, p["y"]))
    def height_of(p):
        lo, hi = yext[p["letter"]]
        return 0 if hi == lo else int(255 * (p["y"] - lo) / (hi - lo))  # 0 = base (smallest y)
    height = [height_of(p) for p in px]
    xs = [p["x"] for p in px]
    xlo, xhi = min(xs), max(xs)
    xnorm = [0 if xhi == xlo else int(255 * (p["x"] - xlo) / (xhi - xlo)) for p in px]
    starts, counts = [], []
    for L in LETTERS:
        idx = [i for i, p in enumerate(px) if p["letter"] == L]
        assert idx == list(range(idx[0], idx[-1] + 1)), "letter %s not contiguous in chain order" % L
        starts.append(idx[0]); counts.append(len(idx))
    return {"num_pixels": n, "num_letters": len(LETTERS), "grid_w": W, "grid_h": H,
            "letter": letter, "col": col, "row": row, "height": height, "xnorm": xnorm,
            "letter_start": starts, "letter_count": counts}

def emit_header(geo, path):
    def arr(name, ctype, vals):
        return "const %s %s[%d] PROGMEM = { %s };\n" % (
            ctype, name, len(vals), ", ".join(str(v) for v in vals))
    out = ["// Generated by tools/gen_wiring.py via tools/charge_geometry.py — DO NOT EDIT.\n",
           "// Regenerate with the ledmap (same WORD_CELL_MM) so COL/ROW stay in sync.\n",
           "#pragma once\n",
           "#define CHARGE_NUM_PIXELS  %d\n" % geo["num_pixels"],
           "#define CHARGE_NUM_LETTERS %d\n" % geo["num_letters"],
           "#define CHARGE_GRID_W      %d\n" % geo["grid_w"],
           "#define CHARGE_GRID_H      %d\n" % geo["grid_h"],
           arr("CHARGE_LETTER", "uint8_t", geo["letter"]),
           arr("CHARGE_COL", "uint8_t", geo["col"]),
           arr("CHARGE_ROW", "uint8_t", geo["row"]),
           arr("CHARGE_HEIGHT", "uint8_t", geo["height"]),
           arr("CHARGE_XNORM", "uint8_t", geo["xnorm"]),
           arr("CHARGE_LETTER_START", "uint16_t", geo["letter_start"]),
           arr("CHARGE_LETTER_COUNT", "uint16_t", geo["letter_count"])]
    open(path, "w").write("".join(out))
