#!/usr/bin/env python3
"""Generate per-piece build inputs from the panelizer output (word_cuts.json):
  - src/parts/word_layout.scad  (paths, per-piece segs/pixels/masks/screws/ties/labels)
  - src/parts/fuzz_piece_N.dat  (V3 fuzzy-top grids sized per piece)
  - build_pieces.sh             (openscad + make_3mf commands for all pieces)
Geometry itself lives in src/parts/piece.scad (PIECE/COL via -D).

Usage: gen_pieces.py [src/parts/word_cuts.json]
"""
import json, math, subprocess, sys

src = sys.argv[1] if len(sys.argv) > 1 else "src/parts/word_cuts.json"
d = json.load(open(src))
paths, cuts, pieces, pixels = d["paths"], d["cuts"], d["pieces"], d["pixels"]
fx0, fy0, fx1, fy1 = d["face"]
BAND = d["band_out"]
TIE_STEP, TIE_OFF = 60.0, 15.5     # zip-tie pairs along the path (transport insurance)

def plen(p):
    return sum(math.dist(p[i], p[i+1]) for i in range(len(p)-1))
def point_tan(p, t):
    acc = 0.0
    for i in range(len(p)-1):
        dd = math.dist(p[i], p[i+1])
        if acc + dd >= t and dd > 0:
            f = (t-acc)/dd
            x = p[i][0]+(p[i+1][0]-p[i][0])*f; y = p[i][1]+(p[i+1][1]-p[i][1])*f
            return (x, y), ((p[i+1][0]-p[i][0])/dd, (p[i+1][1]-p[i][1])/dd)
        acc += dd
    dd = math.dist(p[-2], p[-1]) or 1
    return tuple(p[-1]), ((p[-1][0]-p[-2][0])/dd, (p[-1][1]-p[-2][1])/dd)
def cut_at(c, y):
    return c[min(range(len(c)), key=lambda i: abs(c[i][1]-y))][0]
def side(pt, i):        # True if pt belongs to piece i
    return ((i == 0 or pt[0] > cut_at(cuts[i-1], pt[1])) and
            (i == len(pieces)-1 or pt[0] <= cut_at(cuts[i], pt[1])))

def centroid(p):
    return (sum(q[0] for q in p)/len(p), sum(q[1] for q in p)/len(p))
piece_segs = [[si for si, p in enumerate(paths) if side(centroid(p), i)]
              for i in range(len(pieces))]
piece_px = [[px for px in pixels if side(px, i)] for i in range(len(pieces))]
assert sum(len(s) for s in piece_segs) == len(paths), "segment/piece assignment mismatch"

# piece masks: left boundary bottom->top + right boundary top->bottom (auto-closes)
def boundary(i, left):
    if left and i == 0:
        return [[fx0-1, fy0-2], [fx0-1, fy1+2]]
    if not left and i == len(pieces)-1:
        return [[fx1+1, fy0-2], [fx1+1, fy1+2]]
    c = cuts[i-1] if left else cuts[i]
    pts = sorted(c, key=lambda q: q[1])
    return pts
masks = []
for i in range(len(pieces)):
    lb = boundary(i, True)
    rb = boundary(i, False)
    masks.append(lb + rb[::-1])

# zip-tie holes: pairs flanking the path, kept out of tubes/seams/screws/face edge
all_screws = [s for pc in pieces for s in pc["screws"]]
def path_clear(pt):
    best = 99
    for p in paths:
        for q in p:
            best = min(best, math.dist(pt, q))
            if best < 14:
                return False
    return True
piece_ties = [[] for _ in pieces]
for si, p in enumerate(paths):
    L, t = plen(p), 30.0
    while t < plen(p) - 20:
        (x, y), (tx, ty) = point_tan(p, t)
        for sgn in (1, -1):
            hx, hy = x - ty*TIE_OFF*sgn, y + tx*TIE_OFF*sgn
            if not (fx0+8 < hx < fx1-8 and fy0+8 < hy < fy1-8):
                continue
            if not path_clear((hx, hy)):
                continue
            if any(math.dist((hx, hy), s) < 10 for s in all_screws):
                continue
            pi = next(k for k in range(len(pieces)) if side((hx, hy), k))
            if pi > 0 and abs(hx - cut_at(cuts[pi-1], hy)) < 12:
                continue
            if pi < len(pieces)-1 and abs(hx - cut_at(cuts[pi], hy)) < 12:
                continue
            piece_ties[pi].append([round(hx, 1), round(hy, 1)])
        t += TIE_STEP

# fuzzy-top grids per piece
for i, pc in enumerate(pieces):
    ax, ay = pc["x1"] - pc["x0"] + 6, fy1 - fy0 + 6
    subprocess.run(["python3", "tools/make_fuzz.py", "src/parts/fuzz_piece_%d.dat" % (i+1),
                    "1.5", "0.8", "7", "0", "0", "%.0f" % ax, "%.0f" % ay], check=True)

fmt = lambda pts: "[" + ",".join("[%.2f,%.2f]" % (x, y) for x, y in pts) + "]"
with open("src/parts/word_layout.scad", "w") as f:
    f.write("// AUTO-GENERATED by tools/gen_pieces.py from %s — do not hand-edit\n" % src)
    f.write("wl_face = [%.2f,%.2f,%.2f,%.2f];\n" % (fx0, fy0, fx1, fy1))
    f.write("wl_paths = [\n  %s\n];\n" % ",\n  ".join(fmt(p) for p in paths))
    f.write("wl_piece_segs = %s;\n" % [list(s) for s in piece_segs])
    f.write("wl_piece_px = [\n  %s\n];\n" % ",\n  ".join(fmt(p) for p in piece_px))
    f.write("wl_piece_mask = [\n  %s\n];\n" % ",\n  ".join(fmt(m) for m in masks))
    f.write("wl_piece_scr = [\n  %s\n];\n" % ",\n  ".join(fmt(pc["screws"]) for pc in pieces))
    f.write("wl_piece_tie = [\n  %s\n];\n" % ",\n  ".join(fmt(t) if t else "[]" for t in piece_ties))
    f.write('wl_labels = [%s];\n' % ",".join('"%d%s"' % (i+1, pc["letter"])
                                             for i, pc in enumerate(pieces)))
    f.write("wl_centers = [%s];\n" % ",".join("[%.1f,%.1f]" % ((pc["x0"]+pc["x1"])/2, (fy0+fy1)/2)
                                              for pc in pieces))

with open("build_pieces.sh", "w") as f:
    f.write("#!/usr/bin/env bash\n# AUTO-GENERATED by tools/gen_pieces.py\nset -euo pipefail\n")
    f.write('cd "$(dirname "$0")"\nOSCAD="${OPENSCAD:-openscad}"\nmkdir -p stl\n')
    for i in range(len(pieces)):
        for ci, cn in ((1, "black"), (2, "white"), (3, "clear")):
            f.write('"$OSCAD" -D PIECE=%d -D COL=%d -o stl/piece%d_%s.stl src/parts/piece.scad '
                    '2>stl/p%d%s.log && echo "  ok piece%d_%s"\n' % (i+1, ci, i+1, cn, i+1, cn[0], i+1, cn))
    for i in range(len(pieces)):
        f.write("python3 tools/make_3mf.py stl/piece%d_black.stl stl/piece%d_white.stl "
                "stl/piece%d_clear.stl stl/piece%d_3color.3mf\n" % (i+1, i+1, i+1, i+1))
print("wrote word_layout.scad, fuzz_piece_1..%d.dat, build_pieces.sh" % len(pieces))
for i, pc in enumerate(pieces):
    print("  piece %d (%s): %d segs, %d px, %d ties, %d screws" %
          (i+1, pc["letter"], len(piece_segs[i]), len(piece_px[i]),
           len(piece_ties[i]), len(pc["screws"])))
